### ISSUE TITLE
New component "wxc-form"

### ISSUE THREAD

**Issue by zhoukekestar** [weexteam/weex-components#3]
I have wrote a new component named: `wxc-form`, [github repo](https://github.com/zhoukekestar/wxc-form).
I have already published to [npmjs](https://www.npmjs.com/package/wxc-form).
Any suggestions to let more developers to see it? 😀

**Comment by Jinjiang** [comment]
Great, we will have some discuss about this soon.

**Comment by Jinjiang** [comment]
Hi @zhoukekestar sorry for late to reply. It is really an awesome form component.
This `weex-components` repo is more useful for our official examples. Not so much widely used in productions. So I think it's not very necessary to put `wxc-form` in. Actually it deserves a independent npm package. So I think this status is already absolutely fine :-) And I will share your npm package to more places.
And another thing is Weex will embrace Vue 2.0. We hope to see your more awesome contributions!
Thanks.
