### ISSUE TITLE
Support weex-vue-render

### ISSUE THREAD

**Issue by markzhai** [weexteam/weex-components#4]
Hash: 4c3b81dba0ebe36c2c289dd5d4d240447a5db0ce
Version: webpack 1.14.0
Child
    Hash: 4c3b81dba0ebe36c2c28
    Version: webpack 1.14.0
    Time: 2880ms
           Asset     Size  Chunks             Chunk Names
    index.web.js  66.5 kB       0  [emitted]  index
        + 62 hidden modules
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-0400f665!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-button.we
    template syntax error class="btn btn-{{type}} btn-sz-{{size}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-0400f665!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-button.we
    template syntax error class="btn-txt btn-txt-{{type}} btn-txt-sz-{{size}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-e8f594de!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-hn.we
    template syntax error class="h{{level}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-e8f594de!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-hn.we
    template syntax error class="txt-h{{level}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-2045dfc2!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-list-item.we
    template syntax error style="background-color:{{bgColor}};": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-1e49643d!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-panel.we
    template syntax error class="panel panel-{{type}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-1e49643d!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-panel.we
    template syntax error style="border-width:{{border}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-1e49643d!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-panel.we
    template syntax error class="panel-header panel-header-{{type}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-1e49643d!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-panel.we
    template syntax error style="padding-top:{{paddingHead}};padding-bottom:{{paddingHead}};padding-left:{{paddingHead*1.5}};padding-right:{{paddingHead*1.5}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-1e49643d!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-panel.we
    template syntax error class="panel-body panel-body-{{type}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-1e49643d!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-panel.we
    template syntax error style="padding-top:{{paddingBody}};padding-bottom:{{paddingBody}};padding-left:{{paddingBody*1.5}};padding-right:{{paddingBody*1.5}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-0d1bc0f4!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tip.we
    template syntax error class="tip tip-{{type}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-0d1bc0f4!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tip.we
    template syntax error class="tip-txt tip-txt-{{type}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error style="height:{{height}}; background-color:{{backgroundColor}};": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error data-role="{{dataRole}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error style="color:{{rightItemColor}};": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error if="{{!rightItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error src="{{rightItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error if="{{rightItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error style="color:{{leftItemColor}};": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error if="{{!leftItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error src="{{leftItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error if="{{leftItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-23f06cc7!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navbar.we
    template syntax error style="color:{{titleColor}};": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error data-role="{{dataRole}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error height="{{height}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error background-color="{{backgroundColor}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error title="{{title}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error title-color="{{titleColor}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error left-item-src="{{leftItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error left-item-title="{{leftItemTitle}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error left-item-color="{{leftItemColor}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error right-item-src="{{rightItemSrc}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error right-item-title="{{rightItemTitle}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error right-item-color="{{rightItemColor}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3e31580f!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-navpage.we
    template syntax error style="margin-top:{{height}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error style="visibility:{{visibility}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error repeat="{{tabItems}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error src="{{src}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error repeat="{{tabItems}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error index="{{index}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error icon="{{icon}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error title="{{title}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-7b8e65b9!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabbar.we
    template syntax error title-color="{{titleColor}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-ef4b334e!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabitem.we
    template syntax error style="background-color: {{backgroundColor}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-ef4b334e!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabitem.we
    template syntax error src="{{icon}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div id="{{ val }}">, use <div :id="val">.
    
    ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-ef4b334e!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-components/src/wxc-tabitem.we
    template syntax error style="color: {{titleColor}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div style="{{ val }}">, use <div :style="val">.
    
    ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-components/src/wxc-marquee.we
    Module not found: Error: Cannot resolve module '@weex-module/animation' in /Users/yifan/dev/morecruit/hmb_2c/node_modules/weex-components/src
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-components/src/wxc-marquee.we 53:29-62
Child
    Hash: 9dd5d4d240447a5db0ce
    Version: webpack 1.14.0
    Time: 2960ms
            Asset     Size  Chunks             Chunk Names
    index.weex.js  52.2 kB       0  [emitted]  index
        + 86 hidden modules

**Comment by Jinjiang** [comment]
For Vue 2.0 you can just see here: https://github.com/alibaba/weex/tree/dev/examples/vue/components
They are `weex-components` re-implementation by Vue 2.0
Thanks.
